version: "3.8"
services:
  flight-search:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/flightsdb
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightsdb
    ports:
      - "5432:5432"
