version: "3.8"
services:
  discount-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/discountdb
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discountdb
    ports:
      - "5437:5432"
