version: "3.8"
services:
  auth-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/authdb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
