version: "3.8"
services:
  payment-service:
    build: .
    ports:
      - "7000:7000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/paymentdb
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentdb
    ports:
      - "5436:5432"
